package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.Connection;

public final class knnlinks_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("author: W3layouts\r\n");
      out.write("author URL: http://w3layouts.com\r\n");
      out.write("License: Creative Commons Attribution 3.0 Unported\r\n");
      out.write("License URL: http://creativecommons.org/licenses/by/3.0/\r\n");
      out.write("-->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from demo.w3layouts.com/demos_new/template_demo/06-11-2018/landing_demo_Free/777320977/web/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 17 May 2019 16:42:32 GMT -->\r\n");
      out.write("<!-- Added by HTTrack --><meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\" /><!-- /Added by HTTrack -->\r\n");
      out.write("<head>\r\n");
      out.write("<title>Multiparty Key</title>\r\n");
      out.write("<!-- for-mobile-apps -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Landing Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        addEventListener(\"load\", function () {\r\n");
      out.write("            setTimeout(hideURLbar, 0);\r\n");
      out.write("        }, false);\r\n");
      out.write("\r\n");
      out.write("        function hideURLbar() {\r\n");
      out.write("            window.scrollTo(0, 1);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- animation css files -->\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/animation-aos.css\">\r\n");
      out.write("\t<link href='css/aos.css' rel='stylesheet prefetch' type=\"text/css\" media=\"all\" />\r\n");
      out.write("\t<!-- //animation css files -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- css files -->\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' /><!-- bootstrap css -->\r\n");
      out.write("    <link href=\"css/style.css\" rel='stylesheet' type='text/css' /><!-- custom css -->\r\n");
      out.write("    <link href=\"css/fontawesome-all.css\" rel=\"stylesheet\"><!-- fontawesome css -->\r\n");
      out.write("\t<!-- //css files -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- google fonts -->\r\n");
      out.write("\t<link href=\"http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese\" rel=\"stylesheet\">\r\n");
      out.write("\t<!-- //google fonts -->\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script src='../../../../../../../ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script><script src=\"../../../../../../../m.servedby-buysellads.com/monetization.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("(function(){\r\n");
      out.write("\tif(typeof _bsa !== 'undefined' && _bsa) {\r\n");
      out.write("  \t\t// format, zoneKey, segment:value, options\r\n");
      out.write("  \t\t_bsa.init('flexbar', 'CKYI627U', 'placement:w3layoutscom');\r\n");
      out.write("  \t}\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("(function(){\r\n");
      out.write("if(typeof _bsa !== 'undefined' && _bsa) {\r\n");
      out.write("\t// format, zoneKey, segment:value, options\r\n");
      out.write("\t_bsa.init('fancybar', 'CKYDL2JN', 'placement:demo');\r\n");
      out.write("}\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("(function(){\r\n");
      out.write("\tif(typeof _bsa !== 'undefined' && _bsa) {\r\n");
      out.write("  \t\t// format, zoneKey, segment:value, options\r\n");
      out.write("  \t\t_bsa.init('stickybox', 'CKYI653J', 'placement:w3layoutscom');\r\n");
      out.write("  \t}\r\n");
      out.write("})();\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://services.bilsyndication.com/adv1/?d=353\" defer=\"\" async=\"\"></script><script> var vitag = vitag || {};vitag.gdprShowConsentTool=false;vitag.outStreamConfig = {type: \"slider\", position: \"left\" };</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Global site tag (gtag.js) - Google Analytics -->\r\n");
      out.write("<script async src=\"https://www.googletagmanager.com/gtag/js?id=UA-125810435-1\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("  window.dataLayer = window.dataLayer || [];\r\n");
      out.write("  function gtag(){dataLayer.push(arguments);}\r\n");
      out.write("  gtag('js', new Date());\r\n");
      out.write("\r\n");
      out.write("  gtag('config', 'UA-125810435-1');\r\n");
      out.write("</script><script>\r\n");
      out.write("  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\r\n");
      out.write("  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\r\n");
      out.write("  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\r\n");
      out.write("  })(window,document,'script','../../../../../../../www.google-analytics.com/analytics.js','ga');\r\n");
      out.write("ga('create', 'UA-30027142-1', 'w3layouts.com');\r\n");
      out.write("  ga('send', 'pageview');\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<header class=\"index-banner\">\r\n");
      out.write("    <!-- nav -->\r\n");
      out.write("    <nav class=\"main-header\">\r\n");
      out.write("      <div id=\"brand\" data-aos=\"zoom-in-up\">\r\n");
      out.write("        <div id=\"logo\">\r\n");
      out.write("          <a href=\"index.html\">\r\n");
      out.write("            <i class=\"fab fa-blackberry\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"word-mark\">\r\n");
      out.write("          <h1>\r\n");
      out.write("            <a href=\"index.html\"></a>\r\n");
      out.write("          </h1>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"menu\">\r\n");
      out.write("        <div id=\"menu-toggle\">\r\n");
      out.write("          <div id=\"menu-icon\">\r\n");
      out.write("            <div class=\"bar\"></div>\r\n");
      out.write("            <div class=\"bar\"></div>\r\n");
      out.write("            <div class=\"bar\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"text-center text-capitalize nav-agile\" data-aos=\"zoom-in-up\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"index.html\" class=\"active\">home</a>\r\n");
      out.write("          </li>\r\n");
      out.write("         \r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- //nav -->\r\n");
      out.write("\t<!-- banner -->\r\n");
      out.write("\t<div class=\"banner layer\" id=\"home\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row banner-text\">\r\n");
      out.write("\t\t\t\t<div class=\"slider-info col-lg-8\">\r\n");
      out.write("\t\t\t\t\t<div class=\"agileinfo-logo mt-5\">\r\n");
      out.write("\t\t\t\t\t\t<h2 data-aos=\"fade-down\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fab fa-blackberry text-center\"></span> A Secure Distributed Key On -\r\n");
      out.write("\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<h3 class=\"txt-w3_agile\" data-aos=\"fade-down\">Encrypted information Over Cloud Data </h3>\r\n");
      out.write("\t\t\t\t\t<a class=\"btn mt-4 mr-2 text-capitalize\" data-aos=\"fade-up\" href=\"#\" data-toggle=\"modal\" data-target=\"#exampleModalCenter1\" role=\"button\">About Our Project</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- //banner -->\r\n");
      out.write("</header>\r\n");
      out.write("<!-- //header -->\r\n");
      out.write("<!---728x90--->\r\n");
      out.write("\r\n");
      out.write("<!-- banner bottom -->\r\n");
      out.write("<section class=\"banner-bottom py-5\">\r\n");
      out.write("\t<div class=\"container py-md-3\">\r\n");
      out.write("\t\t<h4 class=\"text-center\" data-aos=\"zoom-in\">Our Trusted Storage Partner</h4>\r\n");
      out.write("\t\t<ul class=\"list-unstyled pt-5 partners-icon text-center\">\r\n");
      out.write("\t\t\t<li data-aos=\"fade-up\">\r\n");
      out.write("\t\t\t\t<i >Drive HQ</i>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li data-aos=\"fade-up\">\r\n");
      out.write("\t\t\t\t<i >MySQL</i>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li data-aos=\"fade-up\">\r\n");
      out.write("\t\t\t\t<i>Tomcat</i>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- //banner bottom -->\r\n");
      out.write("<!---728x90--->\r\n");
      out.write("\r\n");
      out.write("<!-- why choose us -->\r\n");
      out.write("\r\n");
      out.write("<section class=\"pricing bg-light py-5\" id=\"pricing\">\r\n");
      out.write("\t<div class=\"container py-lg-3\">\r\n");
      out.write("\t\t<div class=\"inner-sec\">\r\n");
      out.write("\t\t\t<h3 class=\"heading mb-5 text-center\" data-aos=\"zoom-in\">KNN Min Distance Recomnded Files Info</h3>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


try
{
	Class.forName("com.mysql.jdbc.Driver");
	Connection con3=DriverManager.getConnection("jdbc:mysql://localhost:3306/securedynamic","root","admin");
	Statement stom3=con3.createStatement();
	ResultSet rs3=stom3.executeQuery("Select * from knn_results ");
	
	while(rs3.next())
	{
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h3>");
      out.print(rs3.getString(2) );
      out.write("---------->  MIN Dist------>>");
      out.print(rs3.getInt(4) );
      out.write("------->Suggested Rank Files====>");
      out.print(rs3.getString(3) );
      out.write(" </h3>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");



	}}catch(Exception e){
		
		System.out.println(e);
		
	}



      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- //pricing -->\r\n");
      out.write("\r\n");
      out.write("<!-- faqs -->\r\n");
      out.write("\r\n");
      out.write("<!-- //faqs -->\r\n");
      out.write("\r\n");
      out.write("<!-- testimonials -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--footer -->\r\n");
      out.write("<footer>\r\n");
      out.write("<section class=\"footer footer_w3layouts_section_1its py-5\">\r\n");
      out.write("\t<div class=\"container py-md-4\">\r\n");
      out.write("\t<div class=\"footer-grid_section text-center\" data-aos=\"zoom-in\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-title mb-3\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fab fa-blackberry mr-2\"></i> A Secure Distributed Key On Encrypted Information Over Cloud Data</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"social_section_1info\">\r\n");
      out.write("\t\t\t\t\t<li class=\"mb-2 facebook\"><a href=\"#\"><i class=\"fab mr-1 fa-facebook-f\"></i>facebook</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"mb-2 twitter\"><a href=\"#\"><i class=\"fab mr-1 fa-twitter\"></i>twitter</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"google\"><a href=\"#\"><i class=\"fab mr-1 fa-google-plus-g\"></i>google</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"linkedin\"><a href=\"#\"><i class=\"fab mr-1 fa-linkedin-in\"></i>linkedin</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<div class=\"row footer-top mt-md-5 mt-4\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 footer-grid_section_1its_w3\" data-aos=\"fade-right\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-title\">\r\n");
      out.write("\t\t\t\t\t<h3>Address</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footer-text\">\r\n");
      out.write("\t\t\t\t\t<p>Address : Banglore</p>\r\n");
      out.write("\t\t\t\t\t<p>Phone : +12 534894364</p>\r\n");
      out.write("\t\t\t\t\t<p>Email : <a href=\"mailto:info@example.com\">info@example.com</a></p>\r\n");
      out.write("\t\t\t\t\t<p>Fax : +12 534894364</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-6 mt-md-0 mt-4 footer-grid_section_1its_w3\" data-aos=\"fade-up\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-4 col-md-12 mt-lg-0 mt-4 col-sm-12 footer-grid_section_1its_w3\" data-aos=\"fade-left\">\r\n");
      out.write("\t\t\t\t<div class=\"footer-title\">\r\n");
      out.write("\t\t\t\t\t<h3>Newsletter</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"footer-text\">\r\n");
      out.write("\t\t\t\t\t<p>By subscribing to our mailing list you will always get latest news and updates from us.</p>\r\n");
      out.write("\t\t\t\t\t<form action=\"#\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"email\" name=\"Email\" placeholder=\"Enter your email...\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn1\"><i class=\"fas fa-paper-plane\" aria-hidden=\"true\"></i></button>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</section>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- //footer -->\r\n");
      out.write("\r\n");
      out.write("<!-- copyright -->\r\n");
      out.write("<div class=\"cpy-right text-center py-3\">\r\n");
      out.write("\t<p class=\"\">© 2018 . All rights reserved \r\n");
      out.write("\t\t\r\n");
      out.write("\t</p>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //copyright -->\r\n");
      out.write("\r\n");
      out.write("<!-- Vertically centered Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModalCenter1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalCenter1\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h5 class=\"modal-title text-capitalize text-center\" id=\"exampleModalLongTitle\"> <i class=\"fab fa-blackberry\"></i> Landing</h5>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<img src=\"images/banner.jpg\" class=\"img-fluid mb-3\" alt=\"Modal Image\" />\r\n");
      out.write("\t\t\t\tVivamus eget est in odio tempor interdum. Mauris maximus fermentum arcu, ac finibus ante. Sed mattis risus at ipsum elementum,\r\n");
      out.write("\t\t\t\tut auctor turpis cursus. Sed sed odio pharetra, aliquet velit cursus, vehicula enim. Mauris porta aliquet magna, eget laoreet ligula.\r\n");
      out.write("\t\t\t\tSed mattis risus at ipsum elementum, ut auctor turpis cursus. Sed sed odio pharetra, aliquet.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">Save Changes</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //Vertically centered Modal -->\r\n");
      out.write("\t\r\n");
      out.write("<!-- video Modal Popup -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLabel\">Video Overview</h5>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body video\">\r\n");
      out.write("\t\t\t\t<iframe src=\"https://player.vimeo.com/video/43982091\"></iframe>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-primary\">Save Changes</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- //video Model Popup -->\r\n");
      out.write("\r\n");
      out.write("<!--/Login-->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModalCenter2\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header text-center\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<div class=\"login px-4 mx-auto mw-100\">\r\n");
      out.write("\t\t\t\t\t<h5 class=\"text-center mb-4\">Login Now</h5>\r\n");
      out.write("\t\t\t\t\t<form action=\"UserLogin\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"mb-2\">User name</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"userid\" type=\"text\" required placeholder=\"Username\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\"  required=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<small id=\"emailHelp\" class=\"form-text text-muted\">We'll never share your Username with anyone else.</small>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"mb-2\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input  name=\"password\" type=\"password\" required placeholder=\"Password\"  class=\"form-control\" id=\"exampleInputPassword1\" required=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check mb-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"form-check-input\" id=\"exampleCheck1\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"form-check-label\" for=\"exampleCheck1\">Check me out</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-primary submit mt-2\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text-center pb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#contact\" data-toggle=\"modal2\" data-target=\"#exampleModalCenter\"> Forgot Password?</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--//Login-->\r\n");
      out.write("\r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"js/jquery-2.2.3.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("    <!-- //js -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- animation js -->\r\n");
      out.write("\t<script src='js/aos.js'></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tAOS.init({\r\n");
      out.write("            easing: 'ease-out-back',\r\n");
      out.write("            duration: 1000\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\t<!-- //animation js -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- testimonials  Responsiveslides -->\r\n");
      out.write("    <script src=\"js/responsiveslides.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // You can also use\"$(window).load(function() {\"\r\n");
      out.write("        $(function () {\r\n");
      out.write("            // Slideshow 4\r\n");
      out.write("            $(\"#slider3\").responsiveSlides({\r\n");
      out.write("                auto: true,\r\n");
      out.write("                pager: true,\r\n");
      out.write("                nav: false,\r\n");
      out.write("                speed: 500,\r\n");
      out.write("                namespace: \"callbacks\",\r\n");
      out.write("                before: function () {\r\n");
      out.write("                    $('.events').append(\"<li>before event fired.</li>\");\r\n");
      out.write("                },\r\n");
      out.write("                after: function () {\r\n");
      out.write("                    $('.events').append(\"<li>after event fired.</li>\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- //testimonials  Responsiveslides -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- sticky nav bar-->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(() => {\r\n");
      out.write("\r\n");
      out.write("\t\t  //On Scroll Functionality\r\n");
      out.write("\t\t  $(window).scroll(() => {\r\n");
      out.write("\t\t\tvar windowTop = $(window).scrollTop();\r\n");
      out.write("\t\t\twindowTop > 100 ? $('nav').addClass('navShadow') : $('nav').removeClass('navShadow');\r\n");
      out.write("\t\t\twindowTop > 100 ? $('ul.nav-agile').css('top', '50px') : $('ul.nav-agile').css('top', '160px');\r\n");
      out.write("\t\t  });\r\n");
      out.write("\r\n");
      out.write("\t\t  //Click Logo To Scroll To Top\r\n");
      out.write("\t\t  $('#logo').on('click', () => {\r\n");
      out.write("\t\t\t$('html,body').animate({\r\n");
      out.write("\t\t\t  scrollTop: 0\r\n");
      out.write("\t\t\t}, 500);\r\n");
      out.write("\t\t  });\r\n");
      out.write("\r\n");
      out.write("\t\t /*\r\n");
      out.write("\t\t  //Smooth Scrolling Using Navigation Menu\r\n");
      out.write("\t\t  $('a[href*=\"#\"]').on('click', function (e) {\r\n");
      out.write("\t\t\t$('html,body').animate({\r\n");
      out.write("\t\t\t  scrollTop: $($(this).attr('href')).offset().top - 100\r\n");
      out.write("\t\t\t}, 500);\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t */\r\n");
      out.write("\r\n");
      out.write("\t\t  //Toggle Menu\r\n");
      out.write("\t\t  $('#menu-toggle').on('click', () => {\r\n");
      out.write("\t\t\t$('#menu-toggle').toggleClass('closeMenu');\r\n");
      out.write("\t\t\t$('ul').toggleClass('showMenu');\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('li').on('click', () => {\r\n");
      out.write("\t\t\t  $('ul').removeClass('showMenu');\r\n");
      out.write("\t\t\t  $('#menu-toggle').removeClass('closeMenu');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t  });\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!-- //sticky nav bar -->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/smoothscroll.js\"></script><!-- Smooth scrolling -->\r\n");
      out.write("\r\n");
      out.write("    <!-- start-smoth-scrolling -->\r\n");
      out.write("    <script src=\"js/move-top.js\"></script>\r\n");
      out.write("    <script src=\"js/easing.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        jQuery(document).ready(function ($) {\r\n");
      out.write("            $(\".scroll\").click(function (event) {\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                $('html,body').animate({\r\n");
      out.write("                    scrollTop: $(this.hash).offset().top\r\n");
      out.write("                }, 900);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            /*\r\n");
      out.write("\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\t  containerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t };\r\n");
      out.write("\t\t\t*/\r\n");
      out.write("\r\n");
      out.write("            $().UItoTop({\r\n");
      out.write("                easingType: 'easeOutQuart'\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    <!-- //end-smoth-scrolling -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from demo.w3layouts.com/demos_new/template_demo/06-11-2018/landing_demo_Free/777320977/web/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 17 May 2019 16:42:56 GMT -->\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
